# Generated by Django 2.1.7 on 2019-06-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190604_1209'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paint',
            table='paint',
        ),
    ]
